# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aleksandr.ivanov\PycharmProjects\pythonProject\Client_Server App\UI\Views\ui_format\messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 630)
        MainWindow.setMinimumSize(QtCore.QSize(850, 630))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.message_text = QtWidgets.QTextEdit(self.centralwidget)
        self.message_text.setGeometry(QtCore.QRect(190, 450, 611, 101))
        self.message_text.setObjectName("message_text")
        self.message_lbl = QtWidgets.QLabel(self.centralwidget)
        self.message_lbl.setGeometry(QtCore.QRect(190, 415, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.message_lbl.setFont(font)
        self.message_lbl.setObjectName("message_lbl")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 161, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.contacts_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.contacts_grid.setContentsMargins(0, 0, 0, 0)
        self.contacts_grid.setObjectName("contacts_grid")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 50, 611, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mess_history_grid = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mess_history_grid.setContentsMargins(0, 0, 0, 0)
        self.mess_history_grid.setObjectName("mess_history_grid")
        self.contacts_lbl = QtWidgets.QLabel(self.centralwidget)
        self.contacts_lbl.setGeometry(QtCore.QRect(30, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.contacts_lbl.setFont(font)
        self.contacts_lbl.setObjectName("contacts_lbl")
        self.mess_history_lbl = QtWidgets.QLabel(self.centralwidget)
        self.mess_history_lbl.setGeometry(QtCore.QRect(200, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mess_history_lbl.setFont(font)
        self.mess_history_lbl.setObjectName("mess_history_lbl")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(702, 550, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_lbl.setText(_translate("MainWindow", "Введите сообщение:"))
        self.contacts_lbl.setText(_translate("MainWindow", "Контакты"))
        self.mess_history_lbl.setText(_translate("MainWindow", "История сообщений"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Войти"))
